### ISSUE TITLE
Update `session_durations.csv`

### ISSUE THREAD

**Issue by Jancso** [acqdiv/acqdiv#7]
Due to some corpora updates, file names have changed and therefore the file names in `session_durations.csv` are outdated. This in turn leads to missing durations

We might want to fetch the most recent media files from CHILDES and re-generate `session_durations.csv`.

Both Japanese, Nungon, and Sesotho are affected. Basically, we need to:

- download the updated media
- rerun the get session durations script
- create the csv
- reload the database with the session durations

perhaps useful:

https://github.com/uzling/acqdiv-misc/blob/master/scripts/web/get_files_from_web.sh

https://media.talkbank.org/childes/Other/Sesotho/Demuth/Hlobohang/
https://media.talkbank.org/childes/Other/Sesotho/Demuth/Litlhare/
https://media.talkbank.org/childes/Other/Sesotho/Demuth/TseboNeuoe/
https://media.talkbank.org/childes/Japanese/Miyata/Tai/
https://media.talkbank.org/childes/Japanese/MiiPro/
https://media.talkbank.org/childes/Other/Nungon/Sarvasy/

**Comment by bambooforest** [comment]
See #16

**Comment by Jancso** [comment]
closed via #16
